version: '3.1'

services:
  web:
    build: .
    ports:
      - 80:80
      - 443:443
    links:
      - db
  db:
    image: mariadb
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ss18_lab_imt3501
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
        - ./schema:/docker-entrypoint-initdb.d
