version: '3.1'

services:
  
  web:
    build: .
    ports:
      - "8080:8080"
  redis:
    image: "php:7.2-apache"
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ss18_lab_imt3501
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
        - ./schema:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
